// Generated by CoffeeScript 2.3.2
(function() {
  /*
  My first coffee script tutorial
  */
  var aString, areyouhappy, csOutput, largestNum, name, smallestNum;

  name = "Bharath";

  csOutput = document.getElementById("csoutput");

  csOutput.innerHTML = `Hello ${name}<br>`;

  aString = "I am a String";

  if (typeof aString === 'string') {
    csOutput.insertAdjacentHTML('beforeend', 'astring is a String<br>');
  }

  largestNum = Number.MAX_VALUE;

  smallestNum = Number.MIN_VALUE;

  csOutput.insertAdjacentHTML('beforeend', largestNum + '<br>');

  csOutput.insertAdjacentHTML('beforeend', smallestNum + '<br>');

  areyouhappy = false;

  if (typeof areyouhappy === 'boolean') {
    csOutput.insertAdjacentHTML('beforeend', 'areYouhappy is a boolean<br>');
  }

}).call(this);
